local upgrade_helpers = require "spec/upgrade_helpers"

describe("2.8.1 to master upgrade path", function()
            describe("upgrade #before", function()
                        it("works", function()
                              assert.table_has_column("targets", "cache_key", "text")
                              assert.table_has_column("upstreams", "hash_on_query_arg", "text")
                              assert.table_has_column("upstreams", "hash_fallback_query_arg", "text")
                              assert.table_has_column("upstreams", "hash_on_uri_capture", "text")
                              assert.table_has_column("upstreams", "hash_fallback_uri_capture", "text")
                        end)
            end)
            describe("upgrade #migrating", function()
                        it("works", function()
                              assert.truthy(true)
                        end)
            end)
            describe("upgrade #after", function()
                        it("works", function()
                        end)
            end)
end)
