describe("2.8.1 to master upgrade path", function()
            describe("upgrade #before", function()
                        it("works", function()
                              assert.truthy(true)
                        end)
            end)
            describe("upgrade #migration", function()
                        it("works", function()
                              assert.truthy(true)
                        end)
            end)
            describe("upgrade #after", function()
                        it("works", function()
                              assert.truthy(true)
                        end)
            end)
end)
